import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'
import Stats from './components/Stats'
import Approach from './components/Approach'
import Founders from './components/Founders'
import Call from './components/Call'
import LandingPage from './components/LandingPage'
import 'bootstrap/dist/css/bootstrap.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Surat Digital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className={styles.main}>
      <LandingPage />
      <Stats />
      <Approach />
      <Founders />
      <Call />
      </main>
    </>
  )
}
